### ISSUE TITLE
Use separate dedicated accounts to administer cloud services to minimize the blast radius.

### ISSUE THREAD

**Issue by KingBain** [canada-ca/cloud-guardrails-v2#42]
I really disagree with this point made in guardrail one and I think this a bad pattern.

When I read "Use separate dedicated accounts to administer cloud services to minimize the blast radius.", I dont understand how this is limiting the blast radius. In my head this is still the same blast radius:

- I'm the same person.
- I'm still using the same computer 
- Logging into the same desktop account 
- Accessing the same mailbox.

Having separate accounts is only hiding the name of the actual admin cloud account and hiding isnt the control to resolve this vulnerbility. 

I would much rather focus on using such cloud controls as:

- Implementing MFA
- Implementing JIT(Just in time) access for privalege account escalation. 
	- This is your blast radious reduction
- [stealth edit] Implementing RBAC

**Comment by ptd-tbs** [comment]
Happy to chat more about this one but this provides a good background on why this configuration is being included - https://media.defense.gov/2020/Dec/17/2002554125/-1/-1/0/AUTHENTICATION_MECHANISMS_CSA_U_OO_198854_20.PDF

**Comment by KingBain** [comment]
I can kind of put myself in that head space. That whitepaper talks about a lot of other issues, but this line seems to be where that guardrail and that whitepaper aligning  

"The security of identity federation in any cloud environment directly depends on trust in the on-premises components that perform authentication, assign privileges, and sign SAML tokens. 

Much in the way we do just in time privilege access on the desktops. Push that pattern into the cloud. 

If my desktop credentials get owned at the desktop level, they still need to get my MFA and also get  someone else to approve my JIT access(PIM in Azure) in the cloud

**Comment by mbakernet** [comment]
PTD-TBS, in alignment to the draft Guidance on Cloud authentication for Internal Users, I propose this requirement be changed to

  Ensure adequate protection of cloud administrator accounts

The validation can then be based on the recommended configuration in section 2.3 of that draft guidance, which aligns with what both Kingbains and yourself are proposing.
