### ISSUE TITLE
Configuration of Cloud Marketplaces for cloud profile 1

### ISSUE THREAD

**Issue by KingBain** [canada-ca/cloud-guardrails-v2#43]
If the guardrails are being opened up again this is a perfect opportunity to fix the issue with the cloud marketplaces and cloud profile 1.

Cloud profile 1(Experimentation/Sandbox) being characterized as :
- Cloud-based services used for experimentation/sandbox
- No direct system-to-system network interconnections are required with GC data centers

If I ever wanted to experiment with something in the marketplace, from a 3rd party, I would want to evaluate it in a sandbox before sending it off for approval. If we block the 3rd party marketplace in all the profiles, then I am either out of compliance to do an assessment or I need to use personal cloud accounts or third-party to do assessments.

I feel there should be an exception made with the current profiles regime, making cloud profile 1 exempt from this guardrail.

**Comment by AsmaShams** [comment]
Supply chain integrity check need to be conducted at some level prior to even trying the product in Experimentation/ Sandbox environments. Links to the approved marketplace services to be provided as part of the guidance.
