### ISSUE TITLE
Applicability of Guardrails to Cloud Usage Profiles

### ISSUE THREAD

**Issue by evollebekk** [canada-ca/cloud-guardrails-v2#47]
Will v2 of the cloud guardrails be applied against the cloud usage profiles following the same applicability guidance that was published for v1?

### Links / references
https://github.com/canada-ca/cloud-guardrails/blob/master/EN/00_Applicable-Scope.md

**Comment by fmichaelobrien** [comment]
Eric, Yes, good question
We will be adding/updating the same guidance as a folder like what is in GR V1
Good catch pointing out we are missing the 00 applicable document (we use this page extensively during meets/triage via the link to 
https://github.com/canada-ca/cloud-guardrails/blob/master/EN/00_Applicable-Scope.md
from
https://github.com/canada-ca/accelerators_accelerateurs-gcp/tree/main/deployment-templates/Terraform/guardrails#validation
thanks for that!

Will also updateAlong with the 4 implementations in 
KCC - GR V1 standalone - https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/guardrails
KCC - LZ V2 (embedded GR) -  https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/main/solutions/landing-zone-v2
Terraform GR V1 - https://github.com/canada-ca/accelerators_accelerateurs-gcp
validator - https://github.com/canada-ca/cloud-guardrails-gcp
Terraform PBMM LZ v1 - https://github.com/GoogleCloudPlatform/pbmm-on-gcp-onboarding/tree/main/modules/guardrails
CaC - 

I'll link issue #'s from the implementation repos - here shortly

**Comment by AsmaShams** [comment]
The GC Cloud Usage Profiles are also currently in works to be updated. The update is to align them with the GC Guardrails v2.0 BETA.
