### ISSUE TITLE
05 - Data Location

### ISSUE THREAD

**Issue by KingBain** [canada-ca/cloud-guardrails-v2#48]
Not all cloud providers are created equal and I feel this policy will negatively impact user and developer experience depending on the cloud platform they're working on. 

As an example:

-  GCP has limited offerings for their services in Canada. Ive run into multiple cloud resources where the base service offering is available, but the advanced features are unavailable in our region.

> - Deploying a container registry is available
> - Deploying a fault tolerant multi region container registry unavailable
 
To improve this policy, I think the wording of the policy should also show the steps needed to request an exemption from this policy according to the TBS framework on data residency.

**Comment by KingBain** [comment]
@fmichaelobrien
does GCP have a list of services not available or only partially available in Canada ?

**Comment by fmichaelobrien** [comment]
Good question, there are at least 5 lists, getting the details....
1 - GCP services available only in northamerica-northeast1
2 - GCP services available only in northamerica-northeast2
3 - GCP services available only in both northamerica-northeast1 and northamerica-northeast2
4 - GCP services approved by CCCS for Profile 1-4 and Profile 5-6 available in 1/2/3
5 - GCP services approved by CCCS in 4 and also available in the framework agreement

**Comment by KingBain** [comment]
Any luck with those details @fmichaelobrien  ?

**Comment by gcharest** [comment]
AWS and Azure also have services that are not available in all regions and other services that are labelled as Global or non-region specific:
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/
AWS’s Identity and Access Management is global so that in itself seems to go against this guardrail.
https://learn.microsoft.com/en-us/privacy/eudb/eu-data-boundary-configure-azure-nonregional-services

**Comment by scottnlevac** [comment]
@KingBain there is no exception process for data residency. It's up to your CIO to approve the decision to store data outside of Canada. Policy says its a departmental CIO decision. Refer to section 4.4 https://www.canada.ca/en/government/system/digital-government/guideline-service-digital.html

**Comment by KingBain** [comment]
totally agree, but adding this to the guardrail makes the space needed to have that conversation with the cio.

making that space is so valuable.
