### ISSUE TITLE
Cyber services

### ISSUE THREAD

**Issue by scottnlevac** [canada-ca/cloud-guardrails-v2#57]
How does a department deploy HBS and CBS to SaaS? We have no ability to deploy into the architecture of the underlying service. We can't access to Hosts nor can we access their private network.

**Comment by scottnlevac** [comment]
Same with PaaS now that I think of it

**Comment by nephinj** [comment]
Something to maybe consider as well is if these are offered in all CSP's equally and if not if it should be mandatory or recommended.  I know when we did GCP I don't think there was a CBS available from CCCS.

**Comment by ptd-tbs** [comment]
This guardrail only states to sign an MOU and deploy cyber defense services **where available**. If there is no sensor available for a CSP, then there is no further action required by the department.
