### ISSUE TITLE
GR2 - Manage Access

### ISSUE THREAD

**Issue by gcglinton** [canada-ca/cloud-guardrails-v2#82]
This guardrail is a lot of work for a team, potentially a new one just getting started in Cloud, to achieve in 30 days. If certain documents had templates available, which could be leveraged to increase the time to completion, it could help.

The wording of this guardrail leaves much up for interpretation, and could be clearer, specifically, does "least privilege" imply we _must_ use custom roles? Using built in roles will likely leading to people having more privileges than a custom one, but custom roles will be huge burden to manage. Additionally, not all permissions exist in all providers, and and as a result, roles can't always be applied consistently between cloud providers regardless of whether they're built-in, or custom.

If the intent is more along the line of “using the right role for the job function” then the wording should be modified to be more clear about that.

**Recommendation:**

- Increase timeline for this guardrail, limit its scope, offer guidance for how to apply it on a per-cloud provider basis, or provide boilerplate templates to get people started
- Clear up the intent and wording of the “least privilege” model

**Comment by AsmaShams** [comment]
https://www.cyber.gc.ca/en/guidance/annex-4a-profile-1-protected-b-medium-integrity-medium-availability-itsg-33 (Section 2.4 speaks about least privilege security approach)

GC Accelerators are available for few hyperscalers under FA.
