### ISSUE TITLE
GR7 - Protection of Data-in-Transit

### ISSUE THREAD

**Issue by gcglinton** [canada-ca/cloud-guardrails-v2#86]
Some reference documents point to broken links ([ITSP.40.062](https://www.cse-cst.gc.ca/en/system/files/pdf_documents/itsp.40.062-eng.pdf), and [Considerations for Cryptography in Commercial Cloud Services.](https://www.canada.ca/en/government/system/digital-government/modern-emerging-technologies/cloud-services/government-canada-consideration-use-cryptography-in-cloud.html))

There's been some publications from TBS about [recommendations for TLS server certificates](https://wiki.gccollab.ca/images/9/92/Recommendations_for_TLS_Server_Certificates_-_14_May_2021.pdf), and it would be nice to know how, and if, the cloud provider CA capabilities line up with that policy.

The use of Let's Encrypt is widely available, and free of charge, and while it's referenced, there's no other examples of services that are approved or low risk in the recommendations reference. 

**Recommendation:**

- Fix broken links
- Provide guidance on cloud provider CA capabilities, and the use of Let's Encrypt certificates

**Comment by AsmaShams** [comment]
Links updated. Added CSE Guidance on cloud service cryptography (ITSP.50.106) and  Guidance on defence in depth for cloud-based services (ITSP.50.104).
